defaultSemverRangePrefix: ''

nodeLinker: node-modules

npmRegistries:
  //npm.pkg.github.com/:
    npmAuthToken: '${NPM_TOKEN}'

npmScopes:
  wastewizer:
    npmPublishRegistry: 'https://npm.pkg.github.com'
    npmRegistryServer: 'https://npm.pkg.github.com'

yarnPath: .yarn/releases/yarn-4.11.0.cjs
