name: Release main

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: release-main

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  publish:
    name: Publish
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Node.js
        id: install-node
        uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc
          cache: 'yarn'

      - name: Publish release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn dlx \
          -p semantic-release \
          -p @semantic-release/github \
          semantic-release
